baseURL = "https://themillennialmortgageguy.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"
staticDir = 'static'

[params]
title = "Anthony Pompa"
author = "Anthony Pompa"
description = "I am committed to making your home purchase experience as smooth as possible. My clients become part of my family, and it is my goal to stay with you for life."
profilePicture = "/img/headshot.jpg"
displayMode = "light"
copyright = "NMLS #: 1929191"

[markup.goldmark.renderer]
unsafe= true

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Mortgage Market News"
  weight = 200
  identifier = "news"
  url = "/news/mortgages"